version: 1

update_configs:
  - package_manager: "docker"
    directory: "/5.6/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "python"
          version_requirement: ">= 5.6"

  - package_manager: "docker"
    directory: "/5.7/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "python"
          version_requirement: ">= 5.7"

  - package_manager: "docker"
    directory: "/8.0/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "python"
          version_requirement: ">= 8.0"
