name: Build Docker image

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql-version: [5.6, 5.7, 8.0]
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build --file Dockerfile --tag ${DOCKER_ORGANIZATION_NAME}/${DOCKER_IMAGE_NAME}:${{ matrix.node-version }} ${{ matrix.node-version }}
        env:
          DOCKER_ORGANIZATION_NAME: ${{ secrets.DOCKER_ORGANIZATION_NAME }}
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
