name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Build the Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          push: false

  variants-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['5.6', '5.7', '8.0']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Build the Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          path: ${{ matrix.variant }}
          push: false
