name: build-publish

env:
  DOCKER_IMAGE_NAME: webdevsvc/mysql

on:
  push:
    branches:
      - master

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.2
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          tags: latest
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

  variants-build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['5.6', '5.7', '8.0']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.2
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          path: ${{ matrix.variant }}
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          tags: ${{ matrix.variant }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
